# Notebook 02 – Generación de Datos

## Importaciones

In [1]:
import pandas as pd
import random
from faker import Faker
from datetime import datetime, timedelta

In [2]:
fake = Faker("es_ES")

## Definimos constantes

In [3]:
TOTAL_CLIENTES = 5000
TOTAL_PRODUCTOS = 500
TOTAL_VENTAS = 100000

## Definimos listas de referencia

In [4]:
PAISES = [
    "El Salvador",
    "Guatemala",
    "Honduras",
    "Costa Rica"
]

CATEGORIAS = [
    "Tecnología",
    "Hogar",
    "Ropa",
    "Alimentos",
    "Deportes"
]

SUCURSALES = [
    "San Salvador",
    "Ciudad de Guatemala",
    "Tegucigalpa",
    "San José"
]

In [5]:
PRODUCTOS_POR_CATEGORIA = {
    "Tecnología": [
        "Laptop",
        "Mouse",
        "Teclado",
        "Monitor",
        "Impresora",
        "Tablet",
        "Auriculares",
        "Smartphone",
        "Disco Duro",
        "Webcam"
    ],
    "Hogar": [
        "Sofá",
        "Mesa",
        "Silla",
        "Licuadora",
        "Microondas",
        "Cafetera",
        "Ventilador",
        "Plancha",
        "Lámpara",
        "Estante"
    ],
    "Ropa": [
        "Camiseta",
        "Pantalón",
        "Vestido",
        "Chaqueta",
        "Zapatos",
        "Sudadera",
        "Falda",
        "Blusa",
        "Jeans",
        "Gorra"
    ],
    "Alimentos": [
        "Café",
        "Arroz",
        "Pasta",
        "Galletas",
        "Chocolate",
        "Leche",
        "Jugo",
        "Cereal",
        "Aceite",
        "Azúcar"
    ],
    "Deportes": [
        "Balón",
        "Raqueta",
        "Mancuernas",
        "Bicicleta",
        "Colchoneta",
        "Guantes",
        "Casco",
        "Cronómetro",
        "Botella Deportiva",
        "Cuerda para Saltar"
    ]
}

## Verificación

In [6]:
print(f"Clientes a generar: {TOTAL_CLIENTES}")
print(f"Productos a generar: {TOTAL_PRODUCTOS}")
print(f"Ventas a generar: {TOTAL_VENTAS}")

print("\nPaises:", PAISES)
print("Categorias:", CATEGORIAS)
print("Sucursales:", SUCURSALES)

Clientes a generar: 5000
Productos a generar: 500
Ventas a generar: 100000

Paises: ['El Salvador', 'Guatemala', 'Honduras', 'Costa Rica']
Categorias: ['Tecnología', 'Hogar', 'Ropa', 'Alimentos', 'Deportes']
Sucursales: ['San Salvador', 'Ciudad de Guatemala', 'Tegucigalpa', 'San José']

# Generacion de clientes

In [7]:
def generar_clientes():
    clientes = []

    clientes_por_pais = TOTAL_CLIENTES // len(PAISES)

    id_cliente = 1

    for pais in PAISES:
        for _ in range(clientes_por_pais):
            clientes.append({
                "id_cliente": id_cliente,
                "nombre": fake.name(),
                "pais": pais
            })

            id_cliente += 1

    df_clientes = pd.DataFrame(clientes)

    return df_clientes

In [8]:
df_clientes = generar_clientes()

In [9]:
df_clientes.head()

   id_cliente                            nombre         pais
0           1               Adora Sabater-Saura  El Salvador
1           2         Ruperta Doménech Sandoval  El Salvador
2           3        Kike Rafael Llorente Villa  El Salvador
3           4         Griselda Rocamora Llabrés  El Salvador
4           5  Seve Apolinar Villalobos Mascaró  El Salvador

## Validamos los datos

In [10]:
print("Cantidad total de clientes:", len(df_clientes))

print("\nClientes por pais:")
print(df_clientes["pais"].value_counts())

Cantidad total de clientes: 5000

Clientes por pais:
pais
El Salvador    1250
Guatemala      1250
Honduras       1250
Costa Rica     1250
Name: count, dtype: int64

# Generación de productos

In [11]:
def generar_productos():
    productos = []

    for id_producto in range(1, TOTAL_PRODUCTOS + 1):
        categoria = random.choice(list(PRODUCTOS_POR_CATEGORIA.keys()))
        nombre_base = random.choice(PRODUCTOS_POR_CATEGORIA[categoria])

        productos.append({
            "id_producto": id_producto,
            "producto": f"{nombre_base}",
            "categoria": categoria
        })

    return pd.DataFrame(productos)

In [12]:
df_productos = generar_productos()

In [13]:
df_productos.head()

   id_producto            producto   categoria
0            1          Smartphone  Tecnología
1            2              Laptop  Tecnología
2            3  Cuerda para Saltar    Deportes
3            4             Zapatos        Ropa
4            5               Balón    Deportes

## Validamos los datos

In [14]:
print("Cantidad total de productos:", len(df_productos))

print("\nProductos por categoria:")
print(df_productos["categoria"].value_counts())

Cantidad total de productos: 500

Productos por categoria:
categoria
Tecnología    113
Ropa          105
Hogar          96
Deportes       95
Alimentos      91
Name: count, dtype: int64

# Generación de ventas

In [15]:
def generar_ventas():
    ventas = []

    fecha_inicio = datetime(2026, 1, 1)
    fecha_fin = datetime(2026, 12, 31)

    dias_totales = (fecha_fin - fecha_inicio).days

    for id_venta in range(1, TOTAL_VENTAS + 1):

        fecha_venta = fecha_inicio + timedelta(
            days=random.randint(0, dias_totales)
        )

        ventas.append({
            "id_venta": id_venta,
            "fecha_venta": fecha_venta.date(),
            "id_cliente": random.randint(1, TOTAL_CLIENTES),
            "id_producto": random.randint(1, TOTAL_PRODUCTOS),
            "sucursal": random.choice(SUCURSALES),
            "monto": round(random.uniform(50, 1000), 2)
        })

    return pd.DataFrame(ventas)

In [16]:
df_ventas = generar_ventas()

In [17]:
df_ventas.head()

   id_venta fecha_venta  id_cliente  id_producto             sucursal   monto
0         1  2026-10-02        1058          181  Ciudad de Guatemala  749.16
1         2  2026-04-27        4255          296             San José  666.39
2         3  2026-07-27        4677          250             San José  728.76
3         4  2026-11-02        1374          229          Tegucigalpa  112.82
4         5  2026-10-10         187          132             San José   63.06

## Validamos los datos

In [18]:
print("TOTAL VENTAS:", len(df_ventas))

print("\nFECHAS:")
print(df_ventas["fecha_venta"].min())
print(df_ventas["fecha_venta"].max())

print("\nVENTAS POR SUCURSAL:")
print(df_ventas["sucursal"].value_counts())

TOTAL VENTAS: 100000

FECHAS:
2026-01-01
2026-12-31

VENTAS POR SUCURSAL:
sucursal
San Salvador           25108
Ciudad de Guatemala    25092
San José               24993
Tegucigalpa            24807
Name: count, dtype: int64

# Exportamos el CSV

In [19]:
df_clientes.to_csv("../datasets/clientes.csv", index=False)
df_productos.to_csv("../datasets/productos.csv", index=False)
df_ventas.to_csv("../datasets/ventas.csv", index=False)

print("Archivos exportados correctamente.")

Archivos exportados correctamente.